In [65]:
import pandas as pd
import numpy as np
data = pd.read_csv("model.obj", sep = " ", header = None)
v = np.array(data[data[:][0]=="v"][[1, 2, 3]], dtype = float)

In [66]:
center = np.mean(v, axis = 0)
_, Sigma, vec = np.linalg.svd(v - center)
p = vec[np.argmax(Sigma), :]
p /= np.linalg.norm(p)
proj = np.sum(p * v, axis = 1)
v_start = v[np.argmin(proj), :]
v_end = v[np.argmax(proj), :]
end1 = center - p * np.sum(p * (center - v_start))
end2 = center + p * np.sum(p * (v_end - center))

In [67]:
dis = np.linalg.norm(np.cross(v - center, p), axis = 1)
R = np.max(dis)

In [78]:
ccenter = 0.5*(v_start+v_end)
R,end1,end2, p,ccenter

(0.9767083706717361,
 array([ 0.0196648 , -0.70286207,  2.29314298]),
 array([-0.09250007,  1.93502814, -2.31842034]),
 array([-0.02110781,  0.49641297, -0.86782984]),
 array([0.       , 0.6397265, 0.       ]))

In [73]:
np.sum(p * (v_end - v_start))
ccenter = np.mean(v_start+v_end)

In [79]:
"%."v_end


array([-0.310667,  1.691147, -2.452618])